# Change these first
owner: zebec-protocol # Your GitHub organization or username, where this repository lives
repo: zebec-protocol-status
 # The name of this repository

sites:
  - name: Landing Page
    url: https://zebec.io/
    assignees:
      - regmicmahesh
      - raghibislam
      - abii19
  - name: Application
    url: https://app.zebec.io/
    assignees:
      - regmicmahesh
      - raghibislam
      - abii19
  - name: API 
    url: http://api-v2.zebec.io/ht/
    assignees:
      - regmicmahesh
      - raghibislam
  - name: Legacy API
    url: https://api.zebec.io/
    assignees:
      - regmicmahesh
      - raghibislam
  - name: Legacy Dashboard
    url: https://dashboard.zebec.io/
    assignees:
      - regmicmahesh
      - raghibislam
      - abii19

status-website:
  cname: status.zebec.io
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Zebec Protocol Uptime Monitor
  introTitle: Monitor the status of Zebec Protocol Website / Services using this repository.
  #introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Zebec Protocol
      href: https://zebec.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
